/**
 * This class is generated automatically and should not be manually edited
 * Last generated by Orchestration Designer at: 2022-DEC-08  01:10:50 PM
 */
package english.sms;

public class review extends com.avaya.sce.runtime.SMS { 

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for review
	 */ 
	public review() { 

		//{{START:CLASS:CONSTRUCTOR
		super();
		setSMSMessage("Thanks for your valuble review on the hotel. Looking forward for an another \r\n" +
			"occasion of your visit to our hotel._{message:user}_");
		//}}END:CLASS:CONSTRUCTOR

	} 
} 