package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2022-DEC-07  12:11:33 PM
 */
public class Audio extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(28);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: bookingId
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "bookingId", "bookingid.wav", "Please enter your Booking ID"); 

		// phrase: noinput
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "noinput", "noinput.wav", "No input is provided"); 

		// phrase: noMatch
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "noMatch", "nomatch.wav", "Input provided is incorrect"); 

		// phrase: question1
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "question1", "Question1.wav", "How was your experience at the check-in process of the hotel?"); 

		// phrase: question2
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "question2", "Question2.wav", "How clean was the room at the time of your arrival?"); 

		// phrase: question3
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "question3", "Question3.wav", "How was the food provided at the restaurant?"); 

		// phrase: question4
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "question4", "Question4.wav", "Overall how was your experience in staying in this hotel?"); 

		// phrase: MaxLimit
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MaxLimit", "MaxLimit.wav", "Exceeded maximum input limit"); 

		// phrase: Lang
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "Lang", "language.wav", "Press 1 for English,  Press 2 for Tamil"); 

		// phrase: Tharun
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "Tharun", "Tharun.wav", ""); 

		// phrase: Susee
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "Susee", "Susee.wav", ""); 

		// phrase: Invalid
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "Invalid", "Invalid.wav", ""); 

		// phrase: chooseValid
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "chooseValid", "chooseValid.wav", ""); 

		// phrase: Welcome
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "Welcome", "welcome.au", "Welcome to Booking.com"); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2022-DEC-22  05:08:13 PM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(Audio.PHRASE_MAP, phraseName));
	}
}
