package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2022-DEC-07  12:11:33 PM
 */
public class Audio extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(18);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: lang
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "lang", "language.wav", ""); 

		// phrase: bookingId
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "bookingId", "bookingid.wav", ""); 

		// phrase: noinput
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "noinput", "noinput.wav", ""); 

		// phrase: noMatch
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "noMatch", "nomatch.wav", ""); 

		// phrase: question1
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "question1", "Question1.wav", ""); 

		// phrase: question2
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "question2", "Question2.wav", ""); 

		// phrase: question3
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "question3", "Question3.wav", ""); 

		// phrase: question4
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "question4", "Question4.wav", ""); 

		// phrase: welcome
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "welcome", "welcome.wav", ""); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2022-DEC-08  06:44:39 PM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(Audio.PHRASE_MAP, phraseName));
	}
}
